
import React from 'react';
import { 
  Settings, 
  ChevronLeft, 
  Pause, 
  Play, 
  RotateCcw, 
  Eraser, 
  Pencil, 
  Undo2, 
  Check, 
  Volume2,
  VolumeX,
  Eye,
  Trash2,
  X,
  ShoppingBag,
  Diamond,
  Video,
  Smartphone,
  Zap,
  ScanLine,
  Gift,
  Clock,
  Sun,
  Moon,
  Laptop,
  Lock,
  LockOpen,
  Film,
  BarChart3,
  Hand,
  BatteryCharging,
  Sparkles,
  CassetteTape,
  Wind,
  Drum,
  Share,
  Info,
  Search,
  Keyboard,
  Gamepad2,
  Droplets,
  Music,
  Smile,
  StickyNote,
  Trees,
  GlassWater,
  Bell,
  Heart
} from 'lucide-react';

export const Icons = {
  Settings: (props: any) => <Settings {...props} />,
  Back: (props: any) => <ChevronLeft {...props} />,
  Pause: (props: any) => <Pause {...props} />,
  Play: (props: any) => <Play {...props} />,
  Reset: (props: any) => <RotateCcw {...props} />,
  Erase: (props: any) => <Eraser {...props} />,
  Pencil: (props: any) => <Pencil {...props} />,
  Undo: (props: any) => <Undo2 {...props} />,
  Check: (props: any) => <Check {...props} />,
  Sound: (props: any) => <Volume2 {...props} />,
  Mute: (props: any) => <VolumeX {...props} />,
  Eye: (props: any) => <Eye {...props} />,
  Trash: (props: any) => <Trash2 {...props} />,
  Close: (props: any) => <X {...props} />,
  Store: (props: any) => <ShoppingBag {...props} />,
  Diamond: (props: any) => <Diamond {...props} />, // Using Diamond as Rhombus
  Video: (props: any) => <Video {...props} />,
  // Added Smartphone to match usage in constants.ts
  Smartphone: (props: any) => <Smartphone {...props} />,
  Vibration: (props: any) => <Smartphone {...props} />,
  Auto: (props: any) => <Zap {...props} />,
  Scan: (props: any) => <ScanLine {...props} />,
  Reveal: (props: any) => <Eye {...props} />,
  Gift: (props: any) => <Gift {...props} />,
  Clock: (props: any) => <Clock {...props} />,
  Sun: (props: any) => <Sun {...props} />,
  Moon: (props: any) => <Moon {...props} />,
  System: (props: any) => <Laptop {...props} />,
  Lock: (props: any) => <Lock {...props} />,
  LockOpen: (props: any) => <LockOpen {...props} />,
  Film: (props: any) => <Film {...props} />,
  BarChart: (props: any) => <BarChart3 {...props} />,
  Hand: (props: any) => <Hand {...props} />,
  Battery: (props: any) => <BatteryCharging {...props} />,
  Sparkles: (props: any) => <Sparkles {...props} />,
  Cassette: (props: any) => <CassetteTape {...props} />,
  Wind: (props: any) => <Wind {...props} />,
  Drum: (props: any) => <Drum {...props} />,
  Share: (props: any) => <Share {...props} />,
  Info: (props: any) => <Info {...props} />,
  Keyboard: (props: any) => <Keyboard {...props} />,
  Gamepad: (props: any) => <Gamepad2 {...props} />,
  Droplets: (props: any) => <Droplets {...props} />,
  Music: (props: any) => <Music {...props} />,
  Smile: (props: any) => <Smile {...props} />,
  Paper: (props: any) => <StickyNote {...props} />,
  Wood: (props: any) => <Trees {...props} />,
  Water: (props: any) => <Droplets {...props} />, 
  Bell: (props: any) => <Bell {...props} />,
  Heart: (props: any) => <Heart {...props} />,
};
