import { useCallback, useEffect, useRef, useState } from 'react';

type TactileId = string | number;

export const useTactilePress = <T extends TactileId>() => {
    const [pressedId, setPressedId] = useState<T | null>(null);
    const lockedRef = useRef(false);
    const pressedIdRef = useRef<T | null>(null);
    const pressStartedAtRef = useRef(0);
    const releaseTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
    const actionTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
    const unlockTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

    useEffect(() => () => {
        if (releaseTimerRef.current) clearTimeout(releaseTimerRef.current);
        if (actionTimerRef.current) clearTimeout(actionTimerRef.current);
        if (unlockTimerRef.current) clearTimeout(unlockTimerRef.current);
    }, []);

    const beginPress = useCallback((id: T) => {
        if (lockedRef.current) return;

        pressedIdRef.current = id;
        pressStartedAtRef.current = performance.now();
        setPressedId(id);
    }, []);

    const cancelPress = useCallback((id: T) => {
        if (lockedRef.current || pressedIdRef.current !== id) return;

        pressedIdRef.current = null;
        setPressedId(null);
    }, []);

    const runPressCycle = useCallback((
        id: T,
        action: () => void,
        options?: {
            holdPressedThroughAction?: boolean;
            actionDelayMs?: number;
        },
    ) => {
        if (lockedRef.current) return;

        const startedWithPointer = pressedIdRef.current === id;
        const elapsedPressTime = startedWithPointer
            ? performance.now() - pressStartedAtRef.current
            : 0;
        const releaseDelay = startedWithPointer
            ? Math.max(0, 50 - elapsedPressTime)
            : 50;

        // Lock synchronously so iOS's compatibility click cannot start a
        // second visual cycle before React has rendered the first one.
        lockedRef.current = true;
        if (!startedWithPointer) {
            pressedIdRef.current = id;
            setPressedId(id);
        }

        if (!options?.holdPressedThroughAction) {
            releaseTimerRef.current = setTimeout(() => {
                pressedIdRef.current = null;
                setPressedId(null);
                releaseTimerRef.current = null;
            }, releaseDelay);
        }

        actionTimerRef.current = setTimeout(() => {
            action();
            if (options?.holdPressedThroughAction) {
                pressedIdRef.current = null;
                setPressedId(null);
            }
            actionTimerRef.current = null;

            // Keep the guard briefly after the action to absorb the synthetic
            // follow-up click generated by some iOS WebView tap paths.
            unlockTimerRef.current = setTimeout(() => {
                lockedRef.current = false;
                unlockTimerRef.current = null;
            }, 300);
        }, releaseDelay + (options?.actionDelayMs ?? 80));
    }, []);

    return {
        pressedId,
        beginPress,
        cancelPress,
        runPressCycle,
    };
};
